# Generated by Django 5.0.1 on 2024-02-01 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee_designation',
            fields=[
                ('des_id', models.AutoField(primary_key=True, serialize=False)),
                ('des_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='food_category',
            fields=[
                ('fc_id', models.AutoField(primary_key=True, serialize=False)),
                ('fc_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('package_types', models.CharField(db_column='package types', max_length=20)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('e_id', models.AutoField(primary_key=True, serialize=False)),
                ('e_name', models.CharField(max_length=20)),
                ('contact', models.IntegerField()),
                ('d_o_b_field', models.DateField(db_column='D.O.B.')),
                ('gender', models.CharField(max_length=5)),
                ('shift', models.CharField(max_length=7)),
                ('address', models.CharField(max_length=30)),
                ('salary', models.IntegerField()),
                ('desig', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hotelpro.employee_designation')),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('f_id', models.AutoField(primary_key=True, serialize=False)),
                ('f_name', models.CharField(max_length=255)),
                ('f_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('f_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hotelpro.food_category')),
            ],
        ),
    ]
