# Generated by Django 5.0.1 on 2024-02-05 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotelpro', '0002_room'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Food',
        ),
    ]
