# Generated by Django 5.0.1 on 2024-02-05 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelpro', '0003_delete_food'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('f_id', models.AutoField(primary_key=True, serialize=False)),
                ('f_name', models.CharField(max_length=255)),
                ('f_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('f_img', models.ImageField(upload_to='upload/')),
                ('f_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hotelpro.food_category')),
            ],
        ),
    ]
