# Generated by Django 5.0.1 on 2024-02-06 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotelpro', '0004_food'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Packages',
        ),
    ]
