# Generated by Django 5.0.1 on 2024-02-06 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelpro', '0005_delete_packages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('package_types', models.CharField(db_column='package types', max_length=20)),
                ('package_details', models.TextField(max_length=800)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
