# Generated by Django 5.0.1 on 2024-02-22 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelpro', '0006_packages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('cus_id', models.IntegerField(primary_key=True, serialize=False)),
                ('cus_first_name', models.CharField(max_length=25)),
                ('cus_last_name', models.CharField(max_length=25)),
                ('cus_email', models.CharField(max_length=30)),
                ('cus_password', models.CharField(max_length=16)),
                ('cus_gender', models.CharField(max_length=10)),
                ('cus_mobileno', models.BigIntegerField()),
                ('cus_address', models.CharField(max_length=100)),
            ],
        ),
    ]
