# Generated by Django 5.0.1 on 2024-02-22 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelpro', '0007_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='cus_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='cus_mobileno',
            field=models.IntegerField(max_length=10, unique=True),
        ),
    ]
