# Generated by Django 5.0.1 on 2024-02-22 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelpro', '0008_alter_customer_cus_id_alter_customer_cus_mobileno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='cus_email',
            field=models.CharField(blank=True, max_length=50, verbose_name='email address'),
        ),
    ]
