# Generated by Django 5.0.1 on 2024-02-22 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotelpro', '0009_alter_customer_cus_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
