# Generated by Django 5.0.1 on 2024-02-22 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelpro', '0010_delete_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('cus_id', models.AutoField(primary_key=True, serialize=False)),
                ('cus_first_name', models.CharField(max_length=25)),
                ('cus_last_name', models.CharField(max_length=25)),
                ('cus_user', models.CharField(max_length=30, unique=True)),
                ('cus_email', models.CharField(blank=True, max_length=50, verbose_name='email address')),
                ('cus_password', models.CharField(max_length=16)),
                ('cus_gender', models.CharField(max_length=10)),
                ('cus_mobileno', models.IntegerField(max_length=10, unique=True)),
                ('cus_address', models.CharField(max_length=100)),
            ],
        ),
    ]
