# Generated by Django 5.0.1 on 2024-02-23 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotelpro', '0011_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='cus_address',
        ),
    ]
