# Generated by Django 5.0.1 on 2024-03-21 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotelpro', '0012_remove_customer_cus_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
