# Generated by Django 5.0.1 on 2024-03-21 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotelpro', '0014_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
