# Generated by Django 5.0.1 on 2024-03-24 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotelpro', '0016_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='room',
        ),
    ]
