# Generated by Django 5.0.1 on 2024-03-24 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelpro', '0017_delete_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.AutoField(primary_key=True, serialize=False)),
                ('room_img', models.ImageField(upload_to='upload/')),
                ('room_name', models.CharField(max_length=100)),
                ('room_descri', models.TextField(max_length=500)),
                ('room_type', models.CharField(max_length=10)),
                ('room_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ac_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('extra_bed_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
