# Generated by Django 5.0.1 on 2024-03-25 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotelpro', '0019_booking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
