# Generated by Django 5.0.1 on 2024-03-25 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelpro', '0020_delete_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('bid', models.AutoField(primary_key=True, serialize=False)),
                ('check_in', models.DateField(db_column='in')),
                ('check_out', models.DateField(db_column='out')),
                ('email', models.EmailField(max_length=254)),
                ('number', models.IntegerField()),
                ('rid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotelpro.room')),
                ('uid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotelpro.customer')),
            ],
        ),
    ]
