# Generated by Django 5.0.1 on 2024-03-26 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotelpro', '0021_booking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
