# Generated by Django 5.0.1 on 2024-03-26 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelpro', '0022_delete_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('Booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('Booking_cus_id', models.IntegerField()),
                ('Booking_cus_name', models.CharField(max_length=40)),
                ('Booking_cus_email', models.CharField(max_length=50)),
                ('Booking_cus_mobileno', models.BigIntegerField()),
                ('Booking_checkin', models.DateField()),
                ('Booking_checkout', models.DateField()),
                ('Booking_r_number', models.IntegerField()),
                ('Booking_r_type', models.IntegerField()),
                ('Booking_totalprice', models.FloatField()),
            ],
        ),
    ]
