# Generated by Django 5.0.1 on 2024-03-26 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelpro', '0023_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='Booking_r_type',
            field=models.CharField(max_length=50),
        ),
    ]
