# Generated by Django 5.0.1 on 2024-03-27 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelpro', '0024_alter_booking_booking_r_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='Booking_status',
            field=models.CharField(default='Panding Reservation', max_length=50),
        ),
    ]
