# Generated by Django 5.0.1 on 2024-03-27 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotelpro', '0025_booking_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='Booking_status',
            field=models.CharField(default='Pending Reservation', max_length=50),
        ),
    ]
